# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-21 01:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('game_of_thrones', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('climate', models.CharField(max_length=200)),
                ('known_for', models.CharField(max_length=200)),
                ('houses', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='home_region', to='game_of_thrones.House')),
            ],
        ),
    ]
